# permissions for end users to view furnaces.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: furnace-viewer-role
rules:
- apiGroups:
  - furnace.hyperfoil.io
  resources:
  - furnaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - furnace.hyperfoil.io
  resources:
  - furnaces/status
  verbs:
  - get
